### ISSUE TITLE
gcc is using "openat" so we need to merge #94

### ISSUE THREAD

**Issue by peter-jensen** [brushtechnology/fabricate#102]
gcc is now using "openat" which means that frabricate does not work properly with gcc. We, therefore, need to merge #94.
If somebody writes up the correct procedure for performing a merge then I will do it as a one-off.
I would also need the necessary privileges.

Peter

**Comment by chriscz** [comment]
#94 has now been merged! Thanks for pinging us. We're still looking for active maintainers, please respond to #101 if you'd be interested.
